# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import helloWorld_pb2 as helloWorld__pb2


class HelloWorldStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Double = channel.unary_unary(
        '/helloworld.HelloWorld/Double',
        request_serializer=helloWorld__pb2.Int.SerializeToString,
        response_deserializer=helloWorld__pb2.Int.FromString,
        )
    self.Range = channel.unary_stream(
        '/helloworld.HelloWorld/Range',
        request_serializer=helloWorld__pb2.Int.SerializeToString,
        response_deserializer=helloWorld__pb2.Int.FromString,
        )
    self.Sum = channel.stream_unary(
        '/helloworld.HelloWorld/Sum',
        request_serializer=helloWorld__pb2.Int.SerializeToString,
        response_deserializer=helloWorld__pb2.Int.FromString,
        )
    self.DoubleIter = channel.stream_stream(
        '/helloworld.HelloWorld/DoubleIter',
        request_serializer=helloWorld__pb2.Int.SerializeToString,
        response_deserializer=helloWorld__pb2.Int.FromString,
        )


class HelloWorldServicer(object):
  """Interface exported by the server.
  """

  def Double(self, request, context):
    """A simple RPC.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Range(self, request, context):
    """A server-to-client streaming RPC.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Sum(self, request_iterator, context):
    """A client-to-server streaming RPC.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DoubleIter(self, request_iterator, context):
    """A Bidirectional streaming RPC.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloWorldServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Double': grpc.unary_unary_rpc_method_handler(
          servicer.Double,
          request_deserializer=helloWorld__pb2.Int.FromString,
          response_serializer=helloWorld__pb2.Int.SerializeToString,
      ),
      'Range': grpc.unary_stream_rpc_method_handler(
          servicer.Range,
          request_deserializer=helloWorld__pb2.Int.FromString,
          response_serializer=helloWorld__pb2.Int.SerializeToString,
      ),
      'Sum': grpc.stream_unary_rpc_method_handler(
          servicer.Sum,
          request_deserializer=helloWorld__pb2.Int.FromString,
          response_serializer=helloWorld__pb2.Int.SerializeToString,
      ),
      'DoubleIter': grpc.stream_stream_rpc_method_handler(
          servicer.DoubleIter,
          request_deserializer=helloWorld__pb2.Int.FromString,
          response_serializer=helloWorld__pb2.Int.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helloworld.HelloWorld', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
