# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloWorld.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloWorld.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10helloWorld.proto\x12\nhelloworld\"\x14\n\x03Int\x12\r\n\x05value\x18\x01 \x01(\x05\x32\xcc\x01\n\nHelloWorld\x12,\n\x06\x44ouble\x12\x0f.helloworld.Int\x1a\x0f.helloworld.Int\"\x00\x12-\n\x05Range\x12\x0f.helloworld.Int\x1a\x0f.helloworld.Int\"\x00\x30\x01\x12+\n\x03Sum\x12\x0f.helloworld.Int\x1a\x0f.helloworld.Int\"\x00(\x01\x12\x34\n\nDoubleIter\x12\x0f.helloworld.Int\x1a\x0f.helloworld.Int\"\x00(\x01\x30\x01\x62\x06proto3')
)




_INT = _descriptor.Descriptor(
  name='Int',
  full_name='helloworld.Int',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='helloworld.Int.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['Int'] = _INT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Int = _reflection.GeneratedProtocolMessageType('Int', (_message.Message,), {
  'DESCRIPTOR' : _INT,
  '__module__' : 'helloWorld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Int)
  })
_sym_db.RegisterMessage(Int)



_HELLOWORLD = _descriptor.ServiceDescriptor(
  name='HelloWorld',
  full_name='helloworld.HelloWorld',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=55,
  serialized_end=259,
  methods=[
  _descriptor.MethodDescriptor(
    name='Double',
    full_name='helloworld.HelloWorld.Double',
    index=0,
    containing_service=None,
    input_type=_INT,
    output_type=_INT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Range',
    full_name='helloworld.HelloWorld.Range',
    index=1,
    containing_service=None,
    input_type=_INT,
    output_type=_INT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Sum',
    full_name='helloworld.HelloWorld.Sum',
    index=2,
    containing_service=None,
    input_type=_INT,
    output_type=_INT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DoubleIter',
    full_name='helloworld.HelloWorld.DoubleIter',
    index=3,
    containing_service=None,
    input_type=_INT,
    output_type=_INT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLOWORLD)

DESCRIPTOR.services_by_name['HelloWorld'] = _HELLOWORLD

# @@protoc_insertion_point(module_scope)
